name: pyperformance
on:
  workflow_dispatch:
    inputs:
      runner:
        type: choice
        description: Select runner
        required: true
        default: "self-hosted-linux-amd64"
        options:
          - "self-hosted-macos-aarch64"
          - "self-hosted-linux-amd64"
      python:
        type: string
        required: true
        default: 'graalpy-24.0'
        description: Select python
      pyperformance_extra_args:
        type: string
        default: ""
        required: false

# ensure we build everything locally, using wheel builds and allowing the wheel cache to be used
env:
  PIP_NO_BINARY: ":all:"
  PIP_USE_FEATURE: "no-binary-enable-wheel-cache"
  PIP_USE_PEP517: 1

jobs:
  run_benchmarks:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python }}
          cache: 'pip' # caching pip dependencies
      - run: pip install pyperformance==1.11.0
      - run: pyperformance run --inherit-environ LD_LIBRARY_PATH,PIP_NO_BINARY,PIP_USE_FEATURE,PIP_USE_PEP517 -r -o ${{ inputs.python }}.json ${{ inputs.pyperformance_extra_args }}
      - run: cat ${{ inputs.python }}.json
      - name: Store results
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.python }}.json
          path: ${{ inputs.python }}.json
          if-no-files-found: error
